const PASS_HASH='03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4';
// v0.5: simple client-side gate. This prevents normal viewing but is NOT a server-side security boundary.
const P=['北海道','青森県','岩手県','宮城県','秋田県','山形県','福島県','茨城県','栃木県','群馬県','埼玉県','千葉県','東京都','神奈川県','新潟県','富山県','石川県','福井県','山梨県','長野県','岐阜県','静岡県','愛知県','三重県','滋賀県','京都府','大阪府','兵庫県','奈良県','和歌山県','鳥取県','島根県','岡山県','広島県','山口県','徳島県','香川県','愛媛県','高知県','福岡県','佐賀県','長崎県','熊本県','大分県','宮崎県','鹿児島県','沖縄県'];
let D={items:[]},X={items:[]},W={items:[]},R=JSON.parse(localStorage.getItem('speed_regions')||'[]'),current={pref:'兵庫県',city:'神戸市'};
const $=id=>document.getElementById(id);
async function sha(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function unlock(){const h=await sha($('pw').value);const stored=localStorage.getItem('speed_auth');if(h===stored||h===PASS_HASH){localStorage.setItem('speed_auth',h);$('lock').hidden=true;$('app').hidden=false;load()}else{$('lockmsg').textContent='パスワードが違います。';$('lockmsg').className='danger'}}
$('unlock').onclick=unlock;$('pw').addEventListener('keydown',e=>{if(e.key==='Enter')unlock()});
$('logout').onclick=()=>{localStorage.removeItem('speed_auth');location.reload()};
P.forEach(x=>$('pref').insertAdjacentHTML('beforeend',`<option>${x}</option>`));$('pref').value=current.pref;$('city').value=current.city;
$('show').onclick=()=>{current={pref:$('pref').value,city:$('city').value.trim()};render()};
$('save').onclick=()=>{const r={...current};if(!r.city)return alert('市区町村を入力してください');if(!R.some(x=>x.pref===r.pref&&x.city===r.city)){if(R.length>=20)return alert('登録できる地域は最大20件です');R.push(r);localStorage.setItem('speed_regions',JSON.stringify(R));renderRegions()}};
function renderRegions(){$('regions').innerHTML=R.length?R.map((r,i)=>`<div class="region"><button data-i="${i}">${r.pref} ${r.city}</button><button class="sub" data-del="${i}">削除</button></div>`).join(''):'<div class="muted">登録地域はありません。</div>';document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const r=R[b.dataset.i];$('pref').value=r.pref;$('city').value=r.city;current=r;render()});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{R.splice(+b.dataset.del,1);localStorage.setItem('speed_regions',JSON.stringify(R));renderRegions()})}
function esc(s){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[m]))}
function map(q){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`}
function render(){renderRegions();const items=D.items.filter(x=>x.pref===current.pref&&(!current.city||x.city===current.city||!x.city));if(!items.length)$('official').innerHTML='<div class="card muted">この地域の登録済み公式情報はありません。</div>';else $('official').innerHTML=items.map(x=>`<div class="card"><span class="badge">警察公式</span><b>${esc(x.police_station||x.source||'公式情報')}</b><div class="muted">${esc(x.period||'')}</div>${x.routes?.map(r=>`<div class="route"><b>${esc(r.route)}</b><br>時間：${esc(r.time)}<br>規制速度：${esc(r.speed)}<br>${esc(r.reason||'')}<br><a class="mapbtn" target="_blank" rel="noopener" href="${map(current.pref+' '+current.city+' '+r.route)}">地図を見る</a></div>`).join('')||''}<p>${esc((x.notes||[]).join(' / '))}</p></div>`).join('');
const wi=W.items.filter(x=>x.pref===current.pref&&(!x.city||x.city===current.city));$('web').innerHTML=wi.length?wi.map(x=>`<div class="card"><span class="badge">一般Web</span><b>${esc(x.title)}</b><p>${esc(x.summary)}</p><div class="muted">${esc(x.date||'')}</div></div>`).join(''):'<div class="card muted">関連Web情報はまだ登録されていません。</div>';
const xi=X.items.filter(x=>x.pref===current.pref&&(!x.city||x.city===current.city));$('xinfo').innerHTML=xi.length?xi.map(x=>`<div class="card xpost"><span class="badge">X・一般投稿</span><b>${esc(x.author||'')}</b><div class="muted">${esc(x.date||'')}</div><p>${esc(x.text)}</p>${x.url?`<a class="mapbtn" target="_blank" rel="noopener" href="${esc(x.url)}">元投稿を見る</a>`:''}</div>`).join(''):'<div class="card muted">取得済みのX投稿はありません。X API等で取得した公開投稿データをdata/x.jsonに入れると、ここにまとめて表示できます。</div>';
$('maps').innerHTML=`<div class="card">${current.pref} ${current.city}<br><a class="mapbtn" target="_blank" rel="noopener" href="${map(current.pref+' '+current.city)}">選択地域をGoogleマップで開く</a></div>`}
async function load(){try{const [d,x,w]=await Promise.all([fetch('data/speed.json?'+Date.now()).then(r=>r.json()),fetch('data/x.json?'+Date.now()).then(r=>r.json()).catch(()=>({items:[]})),fetch('data/web.json?'+Date.now()).then(r=>r.json()).catch(()=>({items:[]}))]);D=d;X=x;W=w}catch(e){console.error(e)}render()}
renderRegions();
if(localStorage.getItem('speed_auth')){$('lock').hidden=true;$('app').hidden=false;load()}
